function klen = genklen(kpath, lat)
%
% This function converts kpath generated by genkpath to lengthes
% in reciprocal space.
%
% input:
%   kpath: fractional coordinates of kpoints along high-symmetric lines
%   lat: Cartesian coordinates of lattice vectors in REAL space
%
% output:
%   klen: lengthes in reciprocal space, 1*Nk array
%
    % calculate reciprocal lattice vectors
    lat_recip = recip(lat);
    
    % convert fractional coordinates to cartesian coordinates
    kpt_cart = frac2cart(lat_recip, kpath);
    
    % calculate klen
    [nk, foo] = size(kpath);
    klen = zeros(nk, 1);
    klen(1) = 0.0;
    for ik = 2:nk
        dk = kpt_cart(ik,:) - kpt_cart(ik-1,:);
        klen(ik) = klen(ik-1) + sqrt(dk * dk');
    end
